name: Docker Build and Publish

on:
  push:
    branches:
      - tp2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
     
      - name: List directory contents
        run: ls -la

      - name: Copy .env file
        run: |
          cp ./.env .

      - name: Build and push Docker image
        run: |
          docker build -t fannyc13/tp2-image:weather-image .
          docker push fannyc13/tp2-image:weather-image
          
     
